{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "metrics-app-secret",
    "namespace": "metrics-app",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "metrics-app-secret",
        "namespace": "metrics-app",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "PASSWORD": "AgAlRengBs3TGSHYL3vM4NzhU6aQ2tWFRSOiXS14HUO8ICTw+KHrE4ffCX8HEVnBEMvVsAK5E0J74PMvU3TGW16koGTdGa/OA4gaAstVUQBGvV/ixTujUblWNt9q/j6iza7nkVeUDcVlSWduRKMuAOXFs+f74VgNBbFuvtf90ESjBvb8LzvWA3dX0I2UfnEqg85rrfAX7eOK7dp1x0awaN0Fo9t636EOakW9LQL5rSgRqnaM8AOw3dSVefEjjlYBX1r+qqsncpCdrMxmO3WKYaGrod5Bnqn2cQtIurzvZH017BrYy/r5Yp9ALoCXZIrJ0C6JnxqD/HASNlBisT14dL4vrJ06u2hoWGexzfGbaPzj+WKmgO/O6A0pP52M07GOzYeF9b1EEpGQNc5aT6ttek/twDIqR7RkEWvxK+2H22BNuT1snqCgxejPR41le6Dt1mMaL/27RfI0ggERJqOVKybgWQ2vFFq9Xa/s8y1u62vN5/P+p/ACNDwboLGBzSBDN9Rc7JeLE/SmFMuF09GGk632qu4JoXbUNf0VxBfa58zcA+xfBqYT7DyyOylzhlDbP+u8f1Lm46o4/btXaIfbJKtzbAiO+5y/O0ihYE4OKaV0FFZT8nMHFLFSP40WlfV3t/qZBuNJy3VGUjKold4WwbpEVPoFLeJYtEczYsPMFAy0M4zMcYCsIDoALan4qC9FxqeRvgaordNdTKd6"
    }
  }
}
