{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "metrics-app-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "metrics-app-secret",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "opaque"
    },
    "encryptedData": {
      "PASSWORD": "AgAPMkFfH6qpsyS43jZaYJ7MqfNMjeM+0BdTrQn4kua7kjhmkicIX9V8VGMmAETIGQCOt18Eu1I95f/8H2zr9M1JwLtfuzRYV2HMj6G3QzRkqYZiAy5P97MmZe6e85hxc6JPMMgGWmn6dyI7R5eX023Tg+hPmhu9SMciEtI9HhnEnvhaG5thjtomSCLXs9VvzjLrPA3qZlCMkei/4AMxruFrPjqhPsnZTE9L5wpUH56zN9DHCTWP68NqnZdAqPUc0Kx9SwFZmNMqJjuzkdtFhTr/1kaVoR2etOWud+Gb6HFWydVJhO12bEPaS0O6VTo1uuRU7zXkZcdL2Gr4sqG2/9+gyqZV6H/q3lnZJmAj/mss7QyZ+KVEYDFLQtR14/ce/7Jg5u5efveK75mm6jVLIltDgb4IB39m5qX77amm3iRzpt1U4zx0OBevShveCeGMfaK+whSZuZNMMqH6KWpWi131+FFYPdT1G1eSeGTtRT8+1Y8aA3HsgjQmbXBH2jLuzCgFYxXB+SLY/vsWeqGQpjI8EMaiisaJGntDQOwyUmb6TgO73vclCDpXx7Ie0+J7wPyce7t+gU+HDbrZ75u2jvB91eWyLeuIzLhDd3VpfQYDNqd+7nJ/wJ/WFIS53YuxkrK9xMJQYxOqe5HEmL+ar79iogIt1Iq9EHXkOy1Y/EJTVJePK6fHJ8+O3I2HHQS68M92blQbIzspP3oR"
    }
  }
}
