apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metrics-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "metrics-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "metrics-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: metrics-app-secret
                  key: PASSWORD