apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-app.name" . }}-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
      app: {{ include "metrics-app.name" . }}
